// apps/app-react/src/app/components/GithubUser.tsx
interface GithubUserProps {
  id: number;
  name: string;
  image: string;
}

export default function GithubUser(props: GithubUserProps) {
  return (
    <div>
      <img src={props.image} alt="user avatar" width="40" height="40" />
      <h2>{props.name}</h2>
      <p>{props.id}</p>
    </div>
  )
}

// apps/app-ng/src/app/components/github-user.component.ts
import { Component, Input } from '@angular/core';

@Component({
  standalone: true,
  imports: [],
  selector: 'github-user',
  template: `<div>
    <img [src]="image" alt="user avatar" width="40" height="40" />
    <h2>{{ name }}</h2>
    <p>{{ userId }}</p>
  </div>`,
})
export class GitHubUserComponent {
  @Input() userId!: number;
  @Input() name!: string;
  @Input() image!: string;
}
